import { GeneratorContext } from '../generator.js'

/** Default banner marking a file as generated (do-not-edit). */
export const DEFAULT_HEADER = [
  '// AUTO-GENERATED by firebase-contract. Do not edit by hand.',
  '// Source: ${currentContractPath}',
  '// Generated: ${generatedAt} / Updated: ${updatedAt}',
  '// Regenerate with: fbc generate',
].join('\n')

/** Turn raw header text into `//` comment lines; `default` selects the built-in banner. */
export const toHeaderComment = (text: string): string =>
  text === 'default' ? DEFAULT_HEADER : text.split('\n').map(line => `// ${line}`.trimEnd()).join('\n')

/** The configured header in `//` comment form, or `''` when none is configured. */
export const headerFor = (context: GeneratorContext | undefined): string => context?.header ?? ''

/**
 * The header as a leading block list — empty when no header is configured, so
 * generators can spread it without emitting blank lines.
 */
export const headerBlocks = (
  context: GeneratorContext | undefined,
  transform: (header: string) => string = header => header
): string[] => {
  const header = headerFor(context)
  return header ? [transform(header)] : []
}
