# ./.github/workflows/publish.yml
name: Publish

on:
  push:
    branches:
      - main

env:
  NODE_VERSION_FILE: .nvmrc
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_TOKEN }}

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # needed for provenance data generation
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          filter: tree:0
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ${{ env.NODE_VERSION_FILE }}
          registry-url: https://registry.npmjs.org/

      # Trusted Publishing (OIDC) requires npm >= 11.5.1
      - name: Upgrade npm
        run: npm install -g npm@latest
        shell: bash

      - name: Install dependencies
        run: npm ci
        shell: bash

      - name: Print Environment Info
        run: npx nx report
        shell: bash

      - run: npx nx build --project=plugins/builder
      - run: npx nx run-many --target=output --all
      - name: Publish packages
        run: npx nx release publish
        shell: bash